### ISSUE TITLE
Subsequent Commits Fail on IPv6 Indicator if Not Already Normalized

### ISSUE THREAD

**Issue by ghost** [ThreatConnect-Inc/threatconnect-javascript#11]
Commits inside the commit() method for an indicator fail if the input indicator is an IPv6 Address that is not already normalized to the form stored in ThreatConnect.

#### To reproduce:
Run https://github.com/ThreatConnect-Inc/threatconnect-javascript/blob/master/examples/indicator_commit_all.html with the input indicator `ff02::1`
This indicator gets normalized to `ff02:0:0:0:0:0:0:1` in TC.

#### Actual results:
The subsequent commits are called on the original input indicator, which does not exist because it isn't normalized.
```
POST https://sandbox.threatconnect.com/api/v2/indicators/addresses/ff02::1/attributes [HTTP/1.1 404 Not Found 10ms]
{"status":"Failure","message":"The requested resource was not found"}
```

#### Expected results:
Should send subsequent commits to the normalized version of the indicator: `POST https://sandbox.threatconnect.com/api/v2/indicators/addresses/ff02:0:0:0:0:0:0:1/attributes`

**Comment by bcsummers** [comment]
Fixed in master.
