### ISSUE TITLE
Date filter does not work

### ISSUE THREAD

**Issue by wesinator** [ThreatConnect-Inc/threatconnect-javascript#20]
The date filter is not being applied correctly on groups.

Using the following code, the response still includes groups with dateAdded fields older than the filter:
```
var startDate = "2017-07-30";
var dateFilter = new Filter(FILTER.AND);
dateFilter.on("dateAdded", FILTER.GT, startDate);

var groups = tc.groups();
            groups.owner("Owner Org")
            .type(TYPE.INCIDENT)
            .filter(dateFilter)
            .done(function(response) {
                console.log('response', response);
                $('#response-content').append(JSON.stringify(response, null, 4));
            })
            .error(function(response) {
                console.log('error response', response);
            })
            .retrieve(function() {
                while(groups.hasNext()) {
                    groups.next();
                }
            });
```

**Comment by fhightower** [comment]
@wesdawg Thanks for reporting. It looks like the date format in the example is incorrect. The date format of a filter needs to be `YYYYMMDD` (you can see how this looks in an API call here: https://docs.threatconnect.com/en/latest/rest_api/rest_api.html#filtering-groups). I've submitted a PR to correct the example in #24 .

To get the code snippet you posted above working, you would need to change the first line to:

`var startDate = "20170730";`

**Comment by fhightower** [comment]
This issue can be closed.

**Comment by wesinator** [comment]
😕 I'm confused - now it is with hyphens ?
https://docs.threatconnect.com/en/latest/rest_api/groups/groups.html#filters-parameter

**Comment by wesinator** [comment]
ah, https://github.com/ThreatConnect-Inc/threatconnect-developer-docs/issues/218
