### ISSUE TITLE
Json fields in associated indicator retrieval needs to be changed

### ISSUE THREAD

**Issue by fhightower** [ThreatConnect-Inc/threatconnect-javascript#21]
When retrieving indicators associated with a group (and this is likely the same problem when getting indicators associated with an indicator), the json response has the indicator in the `indicators` field rather than `indicator`.

Here is an example response:
```
Object { id: 1234567, indicators: "example.com", ..}
```

You can find an example retrieval script here: https://github.com/ThreatConnect-Inc/threatconnect-javascript/blob/master/examples/group_retrieve_associations.html#L53

**Comment by wesdawg** [comment]
Also, this field is an empty string `""` on file indicators.
